### ISSUE TITLE
UsingConcurrentCollections consumer never quit

### ISSUE THREAD

**Issue by wj1369884616** [LeonardoZ/java-concurrency-patterns#4]
hello ,when thread blocking and received interrupt ，will throw InterruptedException and Thread.currentThread().isInterrupted() will be return false. so UsingConcurrentCollections consumer never quit

**Comment by LeonardoZ** [comment]
Hi, fixed this here a0979fc6feb165cb7589ef9afdae6608293ec2aa.

I'll try to write and investigate further on this topic. 
Thank you for your help!
